
name: Pull Request Docs Check

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    # Grabbing custom dependencies and building as a pdf.
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.7
        mamba-version: "*"
        channels: conda-forge,cantera/label/dev,defaults
        channel-priority: true
        activate-environment: pliers
    - name: Install pliers
      run: |
        pip install -e .
    - name: Install Sphinx dependencies
      run: |
        cd docs
        pip install -r requirements.txt
        sphinx-build -b html . _build
    - name: Create artifact of the html output
      uses: actions/upload-artifact@v2
      with:
        name: DocumentationHTML
        path: docs/_build/