
name: Pull Request Docs Check

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    # Grabbing custom dependencies and building as a pdf.
    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "pip install sphinx-rtd-theme"
        docs-folder: "docs/"